version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certificates:/etc/nginx/ssl   # แมปโฟลเดอร์ ssl ที่เก็บ cert, key
    ports:
      - "443:443"  # เปิดพอร์ต HTTPS
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
